# Generated by Django 5.2.7 on 2025-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(blank=True, max_length=25, null=True)),
                ('date_connection', models.DateTimeField(auto_now_add=True)),
                ('date_deconnexion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-nom'],
            },
        ),
    ]
