# Generated by Django 5.2.7 on 2025-10-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_users', '0002_loginhistory_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
