# Generated by Django 5.2.7 on 2025-10-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_users', '0003_alter_loginhistory_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
