# Generated by Django 5.2.7 on 2025-10-13 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_users', '0004_alter_loginhistory_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='session_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
