# Generated by Django 5.2.7 on 2025-10-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_users', '0005_loginhistory_session_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
    ]
